sudo: false
distro: trusty

language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_install:
    - echo "" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install --no-interaction --prefer-dist

cache:
    directories:
        - bin
        - vendor
        - ~/.composer/cache/files

script:
    - bin/phpspec run -f dot -n
    - bin/php-cs-fixer fix
